In [2]:
import numpy as np
import pandas as pd

## What are Vectorized operations
- Vectorized operations = fast, clean, NumPy-backed operations that work on entire pandas Series/DataFrames at once, without Python loops.

In [3]:
# Example of vectorized operation

a = np.array([1 , 2 , 3 , 4])
display(a)

display(a * 4)   # every element of array 'a' is multiplied by '4' coz array 'a' taken as one vector

array([1, 2, 3, 4])

array([ 4,  8, 12, 16])

### Problem in vectorized operations in vanilla python ( basic )
- Sometimes if any other Data-type is present inside 'list' , 'set' , 'tuple' or 'dictionary' then python's in-built operations will failed to solve the problem

In [4]:
# Example of failing for vanilla python
s = ['cat' , 'mat' , None , 'rat']

[i.startswith('c') for i in s]           # here 'None' data-type will not be accessed by 'startswith()' function
# AttributeError: 'NoneType' object has no attribute 'startswith'

AttributeError: 'NoneType' object has no attribute 'startswith'

### How Pandas solves the problem

- In pandas, the string accessor .str is a specialized interface that allows you to perform vectorized string operations on an entire Series or Index containing text data.

### 1- Why '.str' Is Needed
- A pandas Series is not a plain list of Python strings; therefore, you cannot directly call .lower(), .split(), etc., on the Series.

Ex ⚡

- s = pd.Series(["Aashish", "ENGINEERING", "india"])

  s.lower()     # ERROR

Solution ✅
- s.str.lower()

### 2- How '.str' Works
- '.str' enables vectorized string operations across the entire Series, meaning the operation will run on every element automatically.

In [5]:
s = pd.Series(['cat' , 'mat' , None , 'rat'])
display(s)

# using string accessor 'str' and 'startswith()' function
s.str.startswith('c')

# Note : This operation is fast and optimized due to 'pandas operations' which built on 'numpy' which built on 'C-language'

0     cat
1     mat
2    None
3     rat
dtype: object

0     True
1    False
2     None
3    False
dtype: object

## Working on real world Dataset 'titanic_csv'

In [6]:
df = pd.read_csv('/content/drive/MyDrive/CSV_files/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
# extract 'Name' column only as Series
Names = df['Name']
Names

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

### Common functions on Strings

In [8]:
# lower() : all alphabets of string will become small
Names.str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: object

In [9]:
# upper() : all string aphabets capital
Names.str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: object

In [10]:
# capitalize() : only first alphabet of whole string will be capital
Names.str.capitalize()

0                                Braund, mr. owen harris
1      Cumings, mrs. john bradley (florence briggs th...
2                                 Heikkinen, miss. laina
3           Futrelle, mrs. jacques heath (lily may peel)
4                               Allen, mr. william henry
                             ...
886                                Montvila, rev. juozas
887                         Graham, miss. margaret edith
888             Johnston, miss. catherine helen "carrie"
889                                Behr, mr. karl howell
890                                  Dooley, mr. patrick
Name: Name, Length: 891, dtype: object

In [11]:
# title() : every word ka first alphabet will be capital
Names.str.title()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [12]:
# len() : number of alphabets/characters(including -> spaces) in string
Names.str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [13]:
# strip() : removes leading(in front)/trailing(at end) spaces
Names.str.strip()

# useful function in 'NLP' related tasks

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [14]:
# split() : splits the string on given 'character'
# get() : fetches particular list indexes after splitting

tukde = Names.str.split(',')     # splitting on basis of comma -> ','
display(tukde)

first_name = tukde.str.get(0)    # fetching '0th' item -> 'first_name' from the list of splitted words
display(first_name)


# storing 'first_name' in main dataset
df['first_name'] = first_name

0                             [Braund,  Mr. Owen Harris]
1      [Cumings,  Mrs. John Bradley (Florence Briggs ...
2                              [Heikkinen,  Miss. Laina]
3        [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                            [Allen,  Mr. William Henry]
                             ...
886                             [Montvila,  Rev. Juozas]
887                      [Graham,  Miss. Margaret Edith]
888          [Johnston,  Miss. Catherine Helen "Carrie"]
889                             [Behr,  Mr. Karl Howell]
890                               [Dooley,  Mr. Patrick]
Name: Name, Length: 891, dtype: object

0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: Name, Length: 891, dtype: object

In [15]:
# split and control using 'n' parameter which limits the splitting until given number
display(Names.str.split(',').str.get(1).str.strip().str.split(' ' , n = 1))


# storing 'title' and 'endname' in main dataset now
df[['title' , 'endname']] = Names.str.split(',').str.get(1).str.strip().str.split(' ' , n = 1 , expand = True)               # 'expand = True' for converting 'series' to a 'DataFrame'
df.head()                                               # 'first_name' , 'title' and 'endname' columns are present in the main data now

0                                 [Mr., Owen Harris]
1      [Mrs., John Bradley (Florence Briggs Thayer)]
2                                     [Miss., Laina]
3              [Mrs., Jacques Heath (Lily May Peel)]
4                               [Mr., William Henry]
                           ...
886                                   [Rev., Juozas]
887                          [Miss., Margaret Edith]
888                [Miss., Catherine Helen "Carrie"]
889                               [Mr., Karl Howell]
890                                   [Mr., Patrick]
Name: Name, Length: 891, dtype: object

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,first_name,title,endname
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr.,Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss.,Laina
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs.,Jacques Heath (Lily May Peel)
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr.,William Henry

In [16]:
# replace() : replaces the given string with other string

df['title'] = df['title'].str.replace('Ms.' , 'Miss.')        # 'Ms' is replaced by 'Miss' in 'title' column and changes saved in main dataset
# df['title'] column updated

## Filtering

In [19]:
# startswith() : string started with given character/alphabet
df[df['first_name'].str.startswith('A')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,first_name,title,endname
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr.,William Henry
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S,Andersson,Mr.,Anders Johan
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S,Asplund,Mrs.,Carl Oscar (Selma Augusta Emilia Johansson)
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S,Ahlin,Mrs.,Johan (Johanna Persdotter Larsson)
49,50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.0,1,0,349237,17.8000,NaN,S,Arnold-Franchi,Mrs.,Josef (Josefine Franchi)

In [20]:
# endswith() : ending with given character/alphabet
df[df['endname'].str.endswith('y')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,first_name,title,endname
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr.,William Henry
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S,Saundercock,Mr.,William Henry
56,57,1,2,"Rugg, Miss. Emily",female,21.0,0,0,C.A. 31026,10.5000,NaN,S,Rugg,Miss.,Emily
71,72,0,3,"Goodwin, Miss. Lillian Amy",female,16.0,5,2,CA 2144,46.9000,NaN,S,Goodwin,Miss.,Lillian Amy
136,137,1,1,"Newsom, Miss. Helen Monypeny",female,19.0,0,2,11752,26.2833,D47,S,Newsom,Miss.,Helen Monypeny

In [22]:
# isdigit() : returns 'True' if string having all characters are digits
df['Name'].str.isdigit()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [25]:
# isalpha() : returns 'True' if all string characters are 'alphabets' only
df['first_name'].str.isalpha()

0      True
1      True
2      True
3      True
4      True
       ...
886    True
887    True
888    True
889    True
890    True
Name: first_name, Length: 891, dtype: bool

## Regex ( regular expression ) using contains() function
- used for advanced filtering

In [32]:
# search John in Names in both upper or lower cases
df[Names.str.contains('John' , case = False)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,first_name,title,endname
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,Johnson,Mrs.,Oscar W (Elisabeth Vilhelmina Berg)
41,42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.0,1,0,11668,21.0000,NaN,S,Turpin,Mrs.,William John Robert (Dorothy Ann Wonnacott)
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S,Rogers,Mr.,William John
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S,Doling,Mrs.,John T (Ada Julia Bone)

In [41]:
# find lastnames starting and ending with an vowel
df[df['endname'].str.contains(r'^[aeiouAEIOU].+[aeiouAEIOU]$')]

''' Explanation :
1-  r'...' → raw string to avoid escaping issues.
2-  ^[aeiouAEIOU] → starts with vowel.
3-  .+ → has one or more characters in between.
4-  [aeiouAEIOU]$ → ends with vowel.
'''

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,first_name,title,endname
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,Rice,Master.,Eugene
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0000,NaN,S,Vander Planke,Miss.,Augusta Maria
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0000,B28,NaN,Icard,Miss.,Amelie
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C,Stewart,Mr.,Albert A
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.0,4,2,3101281,7.9250,NaN,S,Andersson,Miss.,Erna Alexandra

In [45]:
# find firstnames strating and ending with consonants
df[df['first_name'].str.contains(r'^[^aeiouAEIOU].+[^aeiouAEIOU]$')]


''' [^aeiouAEIOU] -> '^' inside the list means the complement of aeiouAEIOU which is a 'consonant'

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,first_name,title,endname
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr.,Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss.,Laina
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,Moran,Mr.,James
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,McCarthy,Mr.,Timothy J

## Slicing

In [49]:
# first 4 characters of string
df['Name'].str[:4]

# alternate characters
df['Name'].str[::2]

# reverse the string
df['Name'].str[::-1]

0                                sirraH newO .rM ,dnuarB
1      )reyahT sggirB ecnerolF( yeldarB nhoJ .srM ,sg...
2                                 aniaL .ssiM ,nenikkieH
3           )leeP yaM yliL( htaeH seuqcaJ .srM ,ellertuF
4                               yrneH mailliW .rM ,nellA
                             ...
886                                sazouJ .veR ,alivtnoM
887                         htidE teragraM .ssiM ,maharG
888             "eirraC" neleH enirehtaC .ssiM ,notsnhoJ
889                                llewoH lraK .rM ,rheB
890                                  kcirtaP .rM ,yelooD
Name: Name, Length: 891, dtype: object